### ISSUE TITLE
Add a change to dark theme feature on navigation for both mobile and desktop views. 

### ISSUE THREAD

**Issue by TheNinza** [TheNinza/dsa-visualizer#12]
You can refer to this link https://mui.com/customization/dark-mode/#toggling-color-mode to get information on implementing dark mode toggle with material UI. Make sure to use same Icon Transition in the link mentioned. 

No need to use some global state management library as prop drilling won't affect the performance that much, because the Navigation component is the immediate child of App component.

**Comment by BelideNikhil** [comment]
Hi @TheNinza, 
I would like to work on this issue.
If you assign me this issue, can I add the theme toggler to the right side of the navbar beside navlink.

**Comment by TheNinza** [comment]
hey @BelideNikhil , I appreciate your response, but currently this issue is there for helping our college students to get familiar with open source. So if I get no response from anyone till tomorrow, I will assign this to you.

**Comment by Manoramsharma** [comment]
@TheNinza sir i want to work on this issue

**Comment by TheNinza** [comment]
sure @Manoramsharma , go ahead....

**Comment by Manoramsharma** [comment]
@TheNinza sir any new module is not getting recognized by App.Jsx , why is its so ?

**Comment by Manoramsharma** [comment]
@TheNinza, getting the following error for implementing the given theme Icon Transition.

./node_modules/@mui/icons-material/utils/createSvgIcon.js
Module not found: Can't resolve '@mui/material/utils' in 'C:\Users\HP\Desktop\New folder\dsa-visualizer\node_modules\@mui\icons-material\utils'

**Comment by Manoramsharma** [comment]
Basic switch base transition is done already.

**Comment by TheNinza** [comment]
You can change the switch to logo that is here https://mui.com/customization/dark-mode/#toggling-color-mode 
It will be a better representation for the action. 
Also about that error.... it looks like that you are missing the dependency. Install it with npm

**Comment by arushi2715** [comment]
Hey @TheNinza ,
I want to work on this.
