### ISSUE TITLE
Change the logo from the institute logo to something more relevant to the topic. Create your own or change it to any other non-copyright one

### ISSUE THREAD

**Issue by TheNinza** [TheNinza/dsa-visualizer#3]

**Comment by Sanket2055** [comment]
Hello sir , i would like to contribute please allow me to go ahead  , thank you!

**Comment by TheNinza** [comment]
@Sanket2055 I assigned this to you.. go ahead

**Comment by Sanket2055** [comment]
hello sir , i have created couple of logo's would u like to review them or should i directly add anyone of them ( in the pr )
