### ISSUE TITLE
Make the "List of Experiments" text smaller for mobile devices

### ISSUE THREAD

**Issue by TheNinza** [TheNinza/dsa-visualizer#4]
## Make the "List of Experiments" text smaller for mobile devices
<img width="379" alt="Screenshot 2021-09-28 at 6 55 36 PM" src="https://user-images.githubusercontent.com/62726436/135095681-cc95385f-81cc-4144-9238-868d670d4242.png">

**Comment by Sanket2055** [comment]
hello sir , please assign me this issue , i am ready to create a PR .

**Comment by Sanket2055** [comment]
hello @TheNinza sir , please assign me this task, i have solved this issue will make PR on 1st oct Thank you.

**Comment by harshgupta1249** [comment]
@TheNinza Is this issue still available? I would like to try.
