### ISSUE TITLE
Add a change to dark theme feature on navigation for both mobile and desktop views

### ISSUE THREAD

**Issue by TheNinza** [TheNinza/dsa-visualizer#5]
You can refer to this link https://mui.com/customization/dark-mode/ to get information on implementing dark mode toggle with material UI

**Comment by TheNinza** [comment]
@rajdama ... sure, go ahead

**Comment by Sanket2055** [comment]
helllo sir , i would like to contribute , please  allow me go ahead 
, Thank you!

**Comment by TheNinza** [comment]
@Sanket2055 sorry mate, I already assigned this issue. Do check other issues for contribution.

**Comment by Sanket2055** [comment]
> @Sanket2055 sorry mate, I already assigned this issue. Do check other issues for contribution.

okay sir , no problem

**Comment by rajdama** [comment]
@TheNinza  Is it ok if I use redux to toggle between light and dark mode?

**Comment by TheNinza** [comment]
> @TheNinza Is it ok if I use redux to toggle between light and dark mode?

I was thinking coz Material UI library has already been implemented, leveraging its capabilities should get the work done. Redux for just implementing dark theme might be a little over kill.

 https://mui.com/customization/dark-mode/

Check this one out for implementation with Material UI

**Comment by rajdama** [comment]
But here the problem use the toggle button in navbar. First we have to store a state and based on its value if is true then we have to show dark mode and if it is false we have to show light mode. We must get this state at App.jsx which is not possible as the state is in navbar component. So I was thinking to use redux.

**Comment by TheNinza** [comment]
Yeahh now I get the idea behind using the redux completely. Yeah sure you can implement redux.

**Comment by rajdama** [comment]
You can check  it I have added

**Comment by rajdama** [comment]
Yeahh I will do that

**Comment by rajdama** [comment]
@TheNinza  you can check I have added dark mode.
